---
title: "Analysis"
---


```{r,echo=FALSE,message = FALSE, warning = FALSE}

#master_file<-read.csv(file.choose() ,header = TRUE)
batting<-read.csv("../EDA_Data/Batting.csv",header=TRUE)
pitching<-read.csv("../EDA_Data/Pitching.csv",header=TRUE)
salaries<-read.csv("../EDA_Data/Salaries.csv",header=TRUE)

library(tidyverse)
library(dplyr)
library(ggplot2)

batsal = left_join(batting,salaries, by="playerID")

```

```{r,echo=FALSE,message = FALSE, warning = FALSE}
batting2 = filter(batting, batting$yearID > 1985) %>% select(yearID,H,X2B,X3B,HR,AB,BB,HBP,SF,) %>% na.omit() %>% mutate(TB = H+2*X2B+(3*X3B)+(4*HR)) %>% mutate(SLG = TB/AB) %>% na.omit() %>% mutate(OBP = (H + BB + HBP)/(AB + BB + SF + HBP)) %>% mutate(OPS = SLG + OBP)

table = batting2 %>% group_by(yearID) %>% summarise(avgOPS = mean(OPS))
```

```{r,echo=FALSE}
ggplot(table, aes(x =yearID, y = avgOPS)) + geom_point() + geom_smooth(se=FALSE) + ggtitle("Average OPS Over Time")

```

We can see that average OPS increases during the 90's and then decreases. 

```{r,echo=FALSE,message = FALSE, warning = FALSE}
pitching2 = filter(pitching, pitching$yearID > 1985) %>% select(yearID,ERA) %>% na.omit
table2 = pitching2 %>% group_by(yearID) %>% summarise(avgERA = mean(ERA))
```

```{r,echo=FALSE,message = FALSE, warning = FALSE}
ggplot(table2, aes(x =yearID, y = avgERA)) + geom_point() + geom_smooth(se=FALSE) + ggtitle("Average ERA Over Time")
```

We can see that average ERA increaes until 2000 and the decreases.

```{r,echo=FALSE,message = FALSE, warning = FALSE}
table3 = data.frame(table,table2) %>% mutate(diff = avgERA-avgOPS)
ggplot(table3, aes(x =yearID, y = diff)) + geom_point() + geom_smooth(se=FALSE) + ggtitle("ERA - OPS Over Time")
```

This graph looks very similar to the graph of ERA. This shows that OPS and ERA increased and decreased at a similar rate. 

```{r,echo=FALSE,message = FALSE, warning = FALSE}
batsal2 = filter(batsal, batsal$yearID.x > 1985) %>% select(yearID.x,H,X2B,X3B,HR,AB,BB,HBP,SF,salary,teamID.x) %>% na.omit() %>% mutate(TB = H+2*X2B+(3*X3B)+(4*HR)) %>% mutate(SLG = TB/AB) %>% na.omit() %>% mutate(OBP = (H + BB + HBP)/(AB + BB + SF + HBP)) %>% mutate(OPS = SLG + OBP)

table4 = batsal2 %>% group_by(yearID.x) %>% summarise(avgOPS = mean(OPS), meansalprop=mean(salary)/10000000)

ggplot() + geom_smooth(data=table4, aes(x=yearID.x,y=avgOPS),se=FALSE) + geom_smooth(data=table4, aes(x=yearID.x,y=meansalprop),se=FALSE)
```

The bottom line shows that salaries were increasing quicker when OPS was increasing.


